spring.application.name=financialintelligence

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/financial_db
spring.datasource.username=postgres
spring.datasource.password=postgre123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

alphavantage.api.key=HJCYLUMKZQNUVG1L
alphavantage.base.url=https://www.alphavantage.co/query
